/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Tue Jun 09 15:21:08 2026. */

#include "keesoncloud.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t VersionPostMessage_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, VersionPostMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, VersionPostMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, VersionPostMessage, softwareMajorVersion, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, VersionPostMessage, softwareMinorVersion, softwareMajorVersion, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, VersionPostMessage, softwareReviseVersion, softwareMinorVersion, 0),
    PB_LAST_FIELD
};

const pb_field_t TokenPostMessage_fields[7] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, TokenPostMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, TokenPostMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, TokenPostMessage, softwareMajorVersion, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, TokenPostMessage, softwareMinorVersion, softwareMajorVersion, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, TokenPostMessage, softwareReviseVersion, softwareMinorVersion, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, TokenPostMessage, firmwareLenth, softwareReviseVersion, 0),
    PB_LAST_FIELD
};

const pb_field_t DownloadRangePostMessage_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, DownloadRangePostMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, DownloadRangePostMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, DownloadRangePostMessage, firmwareLenth, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, DownloadRangePostMessage, firmwareStartOffset, firmwareLenth, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, DownloadRangePostMessage, firmwareEndOffset, firmwareStartOffset, 0),
    PB_LAST_FIELD
};

const pb_field_t CliCommand_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, CliCommand, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, CliCommand, timestamp, deviceID, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, CliCommand, command, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t Sensor5secMessage_fields[7] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, Sensor5secMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Sensor5secMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, Sensor5secMessage, sequence, timestamp, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, Sensor5secMessage, status, sequence, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, Sensor5secMessage, heartbeat, status, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, Sensor5secMessage, breathRate, heartbeat, 0),
    PB_LAST_FIELD
};

const pb_field_t Sensor1secMessage_fields[12] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, Sensor1secMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, sequence, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, status, sequence, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, heartbeat, status, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, breathRate, heartbeat, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, sdata, breathRate, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, pdata, sdata, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, sthd, pdata, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, pthd, sthd, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, Sensor1secMessage, sign, pthd, 0),
    PB_LAST_FIELD
};

const pb_field_t Sensor1minMessage_fields[13] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, Sensor1minMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, sequence, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, onOffBed, sequence, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, heartbeat, onOffBed, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, breathRate, heartbeat, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, Mmin, breathRate, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, Mmean, Mmin, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, NSD, Mmean, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, Npd, NSD, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, SBP, Npd, 0),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, Sensor1minMessage, DBP, SBP, 0),
    PB_LAST_FIELD
};

const pb_field_t SleepApneaMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, SleepApneaMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, SleepApneaMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, SleepApneaMessage, sequence, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, SleepApneaMessage, status_flag, sequence, 0),
    PB_LAST_FIELD
};

const pb_field_t SleepApneaBackMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, SleepApneaBackMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, SleepApneaBackMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, SleepApneaBackMessage, sequence, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, SleepApneaBackMessage, back, sequence, 0),
    PB_LAST_FIELD
};

const pb_field_t SleepCycleRepoMessage_fields[17] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, SleepCycleRepoMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, calResult, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, startTime, calResult, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, totalSleepTime, startTime, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, sleepEfficiency, totalSleepTime, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, sleepQuality, sleepEfficiency, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, turnoverTimes, sleepQuality, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, sleepLatency, turnoverTimes, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, offBedTimes, sleepLatency, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, cRSD, offBedTimes, 0),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, slop1, cRSD, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, slop2, slop1, 0),
    PB_FIELD( 14, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, oSATimes, slop2, 0),
    PB_FIELD( 15, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, Ave_SA_time, oSATimes, 0),
    PB_FIELD( 16, INT32   , SINGULAR, STATIC  , OTHER, SleepCycleRepoMessage, Longest_SA_time, Ave_SA_time, 0),
    PB_LAST_FIELD
};

const pb_field_t StateRawDataMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, StateRawDataMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, StateRawDataMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, StateRawDataMessage, data, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, StateRawDataMessage, data_len, data, 0),
    PB_LAST_FIELD
};

const pb_field_t HeartbeatRawDataMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, HeartbeatRawDataMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, HeartbeatRawDataMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, HeartbeatRawDataMessage, data, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, HeartbeatRawDataMessage, data_len, data, 0),
    PB_LAST_FIELD
};

const pb_field_t BreathRawDataMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, BreathRawDataMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, BreathRawDataMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, BreathRawDataMessage, data, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, BreathRawDataMessage, data_len, data, 0),
    PB_LAST_FIELD
};

const pb_field_t MovementRawDataMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, MovementRawDataMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, MovementRawDataMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, MovementRawDataMessage, data, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, MovementRawDataMessage, data_len, data, 0),
    PB_LAST_FIELD
};

const pb_field_t SnoreRawDataMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, SnoreRawDataMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, SnoreRawDataMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, SnoreRawDataMessage, data, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, SnoreRawDataMessage, data_len, data, 0),
    PB_LAST_FIELD
};

const pb_field_t SbpRawDataMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, SbpRawDataMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, SbpRawDataMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, SbpRawDataMessage, data, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, SbpRawDataMessage, data_len, data, 0),
    PB_LAST_FIELD
};

const pb_field_t DbpRawDataMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, DbpRawDataMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, DbpRawDataMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, DbpRawDataMessage, data, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, DbpRawDataMessage, data_len, data, 0),
    PB_LAST_FIELD
};

const pb_field_t BedCommandMessage_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, BedCommandMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, BedCommandMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, BedCommandMessage, cmd, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t BedStatusMessage_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, BedStatusMessage, deviceID, deviceID, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, BedStatusMessage, timestamp, deviceID, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, BedStatusMessage, stat, timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, BedStatusMessage, stat_len, stat, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
